"""source file import model

Revision ID: 811d10323fdd
Revises: c57fd4ad54bf
Create Date: 2026-07-15 13:13:49.692968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '811d10323fdd'
down_revision: Union[str, Sequence[str], None] = 'c57fd4ad54bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sheet_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_files_file_hash'), 'source_files', ['file_hash'], unique=False)
    op.add_column('benchmark_runs', sa.Column('source_file_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_benchmark_runs_source_file_id'), 'benchmark_runs', ['source_file_id'], unique=False)
    op.create_foreign_key(None, 'benchmark_runs', 'source_files', ['source_file_id'], ['id'], ondelete='SET NULL')
    op.drop_column('platform_executions', 'auth_success')
    op.add_column('scenario_results', sa.Column('source_ref', sa.String(length=256), nullable=True))
    op.drop_column('scenario_results', 'source_conversation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_results', sa.Column('source_conversation_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('scenario_results', 'source_ref')
    op.add_column('platform_executions', sa.Column('auth_success', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'benchmark_runs', type_='foreignkey')
    op.drop_index(op.f('ix_benchmark_runs_source_file_id'), table_name='benchmark_runs')
    op.drop_column('benchmark_runs', 'source_file_id')
    op.drop_index(op.f('ix_source_files_file_hash'), table_name='source_files')
    op.drop_table('source_files')
    # ### end Alembic commands ###
