"""initial schema

Revision ID: c57fd4ad54bf
Revises: 
Create Date: 2026-07-15 11:21:34.462135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c57fd4ad54bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('auth_success', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['benchmark_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_executions_run_id'), 'platform_executions', ['run_id'], unique=False)
    op.create_table('scenario_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('platform_execution_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.String(length=128), nullable=False),
    sa.Column('use_case', sa.String(length=128), nullable=False),
    sa.Column('source_conversation_id', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('screenshot_path', sa.String(length=512), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('raw_conversation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['platform_execution_id'], ['platform_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_results_platform_execution_id'), 'scenario_results', ['platform_execution_id'], unique=False)
    op.create_table('turns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_result_id', sa.Uuid(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('turn_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_result_id'], ['scenario_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turns_scenario_result_id'), 'turns', ['scenario_result_id'], unique=False)
    op.create_table('metric_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('turn_id', sa.Uuid(), nullable=False),
    sa.Column('metric_name', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('judge_model', sa.String(length=128), nullable=True),
    sa.Column('rubric_version', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_scores_turn_id'), 'metric_scores', ['turn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_scores_turn_id'), table_name='metric_scores')
    op.drop_table('metric_scores')
    op.drop_index(op.f('ix_turns_scenario_result_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_scenario_results_platform_execution_id'), table_name='scenario_results')
    op.drop_table('scenario_results')
    op.drop_index(op.f('ix_platform_executions_run_id'), table_name='platform_executions')
    op.drop_table('platform_executions')
    op.drop_table('benchmark_runs')
    # ### end Alembic commands ###
